config/routes.rb
Rails.application.routes.draw do

  root to: 'session#home'
  # get '/users/new' => 'users#new'
  # post '/users' => 'users#create'



  # Session routes:
  get  '/login' => 'session#new'     # login form

  # form submits here, do authentication & create session & redirect, or show form with errors
  post '/login' => 'session#create'

  delete '/login' => 'session#destroy'  # logout, i.e. delete session for this user

  post '/workouts/:id' => 'workouts#add_comment'

  # Users CRUD
  resources :users

  # Workouts CRUD
  resources :workouts

  # Exercises CRUD
  resources :exercises

  # Comments CRUD
  resources :comments

end

app/models/workout.rb
class Workout < ApplicationRecord
  has_and_belongs_to_many :exercises

  # has_and_belongs_to_many :liked_by_users, class_name: 'User' #many to many for like/fave

  belongs_to :user, optional: true
  has_many :comments

  validates :workout_type, presence:true
  validates :image, presence:true

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

before_action :check_if_logged_in
  # CREATE ############################################
  def new
    @workout = Workout.new
    @exercises = Exercise.all
  end

  def create
    @workout = Workout.new workout_params

    # Handle upload, if file was uploaded
    if params[:file].present?
      # Actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @workout.image = response['public_id']
    end

    @workout.user_id = @current_user.id

    @workout.save

    if @workout.persisted?

      #because the workout was successfully saved, we can now add the selected exercises as associations

      if params[:exercises].present?
        @workout.exercises << Exercise.find( params[:exercises] )
      end

      if params[:exercise_name].present?
        # If the user has filled out the exercise part of the form, create that new exercise and associate it with this new workout
        exercise = Exercise.create name: params[:exercise_name], reps: params[:exercise_reps], descript: params[:exercise_descript], image: params[:exercise_image], link: params[:exercise_link], tips: params[:exercise_tips]
        @workout.exercises << exercise
      end
      redirect_to workouts_path
    else
      # redirect_to new_user_path
      # show the form again directly, no re-direct. This lets us use the failed @user create object in our template form_for, which gives us access to the validation error messages, and also causes the already submitted fields of the form to be re-populated for the user
      @exercises = Exercise.all
      render :new
    end




  end

  # READ ################################
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find params[:id]
  end

  # UPDATE ####################################

  def edit
    @workout = Workout.find params[:id]
    @exercises = Exercise.all
    redirect_to exercises_path unless @workout.user == @current_user
  end

  def update
    workout = Workout.find params[:id]
    workout.update workout_params

    redirect_to workouts_path
  end

  # DESTROY ################################

  def destroy
    Workout.destroy params[:id]
    redirect_to workouts_path
  end


  def add_comment
    workout = Workout.find params[:id]
    comment = Comment.create!(comment: params[:comment], user_id: @current_user.id)
    workout.comments << comment
    redirect_to workout_path(workout)
  end

  private

  def workout_params
   params.require( :workout ).permit( :workout_type, :image, :description )
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<div class="content">
<%= form_for @workout, html: {multipart: true} do |f| %>

<% if @workout.errors.full_messages.any? %>
  <ul>
    <% @workout.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

<%= f.label :workout_type, 'Name:' %><br>
  <%= f.text_field :workout_type %>
  <br>

  <%= f.label :description, 'Description:' %><br>
    <%= f.text_field :description %>
    <br>

  <%= f.label :image, 'Image:' %><br>
  <%= f.cl_image_upload :image %>
  <br>


  <h4>Add an existing exercise:</h4>
  <% @exercises.each do |exercise| %>
    <%= label_tag do %>
      <%= check_box_tag 'exercises[]', exercise.id %>
      <%= exercise.name %>
    <% end %>
    (<%= link_to 'Preview', exercise_path(exercise.id) %>)
    <br>
  <% end %>

  <h3>Add a new exercise</h3>
    <%= label_tag :exercise_name, 'Name:', class: "name" %>
    <%= text_field_tag :exercise_name %>
    <br>

    <%= label_tag :exercise_descript, 'Description:' %>
    <%= text_field_tag :exercise_descript %>
    <br>

    <%= label_tag :exercise_image, 'Image:' %><br>
    <%= text_field_tag :exercise_image %>
    <br>
    <br>

    <%= label_tag :exercise_reps, 'Reps:' %>
    <%= text_field_tag :exercise_reps %>
    <br>
    <br>

    <%= label_tag :exercise_link, 'Link:' %>
    <%= text_field_tag :exercise_link %>
    <br>
    <br>

    <%= label_tag :exercise_tips, 'Tips:' %>
    <%= text_field_tag :exercise_tips %>
    <br>
    <br>



  <br>
  <br>

  <%= f.submit %>

<% end %>
</div>

app/views/workouts/edit.html.erb
<h2>Edit <%= @workout.workout_type %></h2>
<%= render partial: 'form' %>

app/views/workouts/index.html.erb
<div id="workout_page">
  <div class="final">
<div class="index_workouts">
  <h2>All Workouts</h2>
</div>
<div>
  <% @workouts.each do |workout| %>
    <%# link_to workout.workout_type, workout_path(workout.id) %>
    <% if workout.image.present? %>
      <%= link_to cl_image_tag(workout.image, :class => "workout" ), workout_path(workout.id), alt: workout.workout_type %>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/workouts/new.html.erb
<h2>Add a new workout</h2>

<%= render partial: 'form' %>

app/views/workouts/show.html.erb
<div class="content">
<h2> <%= @workout.workout_type %> </h2>

<% if @current_user.present? && @workout.user_id == @current_user.id %>
  <%= link_to 'Edit Workout', edit_workout_path(@workout.id) %>
  |
  <%= link_to 'Delete Workout', workout_path(@workout.id), method: 'delete' %>
<% end %>


<% @workout.exercises.each do |exercise| %>
  <h5><%= exercise.name %></h5>
  <h5>Image: <br><br><%= cl_image_tag exercise.image %></h5>
  <h5>Description: <br><br><%= exercise.descript %></h5>
  <h5> <a href="<%= exercise.link %>">How to:</a></h5>
  <h5>Reps: <br><br><%= exercise.reps %></h5>
  <h5>Additional tips: <br><br><%= exercise.tips %></h5>
<% end %>
</div>