config/routes.rb
Rails.application.routes.draw do

  root to: 'session#home'
  # get '/users/new' => 'users#new'
  # post '/users' => 'users#create'



  # Session routes:
  get  '/login' => 'session#new'     # login form

  # form submits here, do authentication & create session & redirect, or show form with errors
  post '/login' => 'session#create'

  delete '/login' => 'session#destroy'  # logout, i.e. delete session for this user

  post '/workouts/:id' => 'workouts#add_comment'

  # Users CRUD
  resources :users

  # Workouts CRUD
  resources :workouts

  # Exercises CRUD
  resources :exercises

  # Comments CRUD
  resources :comments

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>
  </head>

  <body>



    <% if controller.action_name != 'home' %>
    <nav class="topnav">
        <% if @current_user.present? %>
          <%# Hello, <%= @current_user.name %>
          <%= link_to 'My Profile', user_path(@current_user)%>
          <%= link_to 'Workouts', workouts_path %>
          <%= link_to 'Create a new Workout ', new_workout_path %>
        <nav class="topnav-right">
          <%= link_to 'Logout', login_path, method: 'delete' %>
        </nav>
        <% else %>
            <%= link_to 'Login',  login_path %>

            <%= link_to 'Sign Up', new_user_path %>
        <% end %>
    </nav>
    <% end %>


    <%= yield %>


  </body>
</html>